# Generated by Django 5.1.7 on 2025-03-22 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版社')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='出版日')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='ページ数')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='表紙画像')),
                ('description', models.TextField(blank=True, verbose_name='概要')),
                ('status', models.CharField(choices=[('not_started', '未読'), ('in_progress', '読書中'), ('completed', '読了'), ('on_hold', '中断'), ('abandoned', '放棄')], default='not_started', max_length=20, verbose_name='状態')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='読み始め日')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='読了日')),
                ('current_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='現在のページ')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='評価')),
                ('review', models.TextField(blank=True, verbose_name='レビュー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '本',
                'verbose_name_plural': '本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='ページ番号')),
                ('highlight', models.BooleanField(default=False, verbose_name='ハイライト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_core.book', verbose_name='本')),
            ],
            options={
                'verbose_name': '読書メモ',
                'verbose_name_plural': '読書メモ',
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='終了時間')),
                ('all_day', models.BooleanField(default=False, verbose_name='終日')),
                ('category', models.CharField(choices=[('study', '勉強'), ('exercise', '運動'), ('meeting', 'ミーティング'), ('reading', '読書'), ('personal', '個人'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='場所')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='繰り返し')),
                ('recurring_pattern', models.CharField(blank=True, help_text='daily, weekly, monthly, yearly', max_length=50, verbose_name='繰り返しパターン')),
                ('recurring_end_date', models.DateField(blank=True, null=True, verbose_name='繰り返し終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'カレンダーイベント',
                'verbose_name_plural': 'カレンダーイベント',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'ライト'), ('dark', 'ダーク'), ('auto', 'システム設定に合わせる')], default='light', max_length=10, verbose_name='テーマ')),
                ('default_view', models.CharField(choices=[('dashboard', 'ダッシュボード'), ('learning', '学習記録'), ('habits', '習慣トラッキング'), ('books', '読書管理'), ('calendar', 'カレンダー'), ('goals', '目標設定')], default='dashboard', max_length=20, verbose_name='デフォルト表示')),
                ('widget_layout', models.JSONField(default=dict, help_text='ダッシュボードのウィジェット配置設定', verbose_name='ウィジェットレイアウト')),
                ('show_streak_counts', models.BooleanField(default=True, verbose_name='連続達成数を表示')),
                ('show_goal_progress', models.BooleanField(default=True, verbose_name='目標進捗を表示')),
                ('show_habit_summary', models.BooleanField(default=True, verbose_name='習慣サマリーを表示')),
                ('show_reading_stats', models.BooleanField(default=True, verbose_name='読書統計を表示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ダッシュボード設定',
                'verbose_name_plural': 'ダッシュボード設定',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限日')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '進行中'), ('completed', '達成済み'), ('abandoned', '放棄')], default='not_started', max_length=20, verbose_name='状態')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='優先度')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='進捗率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_goals', to='app_core.goal', verbose_name='親目標')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '目標',
                'verbose_name_plural': '目標',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='順序')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_steps', to='app_core.goal', verbose_name='目標')),
            ],
            options={
                'verbose_name': '目標ステップ',
                'verbose_name_plural': '目標ステップ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='習慣名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('category', models.CharField(choices=[('study', '勉強'), ('exercise', '運動'), ('reading', '読書'), ('meditation', '瞑想'), ('programming', 'プログラミング'), ('language', '語学'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('target_value', models.FloatField(default=0, verbose_name='目標値')),
                ('unit_of_measure', models.CharField(default='分', max_length=20, verbose_name='単位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '習慣',
                'verbose_name_plural': '習慣',
            },
        ),
        migrations.CreateModel(
            name='LearningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_entries', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '学習記録',
                'verbose_name_plural': '学習記録',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='learning_attachments/', verbose_name='ファイル')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_core.learningentry', verbose_name='学習記録')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('habit_tracker', '習慣トラッカー'), ('goal_progress', '目標進捗'), ('reading_stats', '読書統計'), ('calendar', 'カレンダー'), ('recent_learning', '最近の学習'), ('streak_calendar', 'ストリークカレンダー')], max_length=30, verbose_name='ウィジェットタイプ')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='表示位置')),
                ('settings', models.JSONField(default=dict, verbose_name='設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ウィジェット',
                'verbose_name_plural': 'ウィジェット',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('content', models.TextField(verbose_name='内容')),
                ('mood', models.CharField(blank=True, max_length=50, verbose_name='気分')),
                ('productivity_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='生産性評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_journals', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '日記',
                'verbose_name_plural': '日記',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='進捗率')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='app_core.goal', verbose_name='目標')),
            ],
            options={
                'verbose_name': '目標進捗',
                'verbose_name_plural': '目標進捗',
                'ordering': ['-date'],
                'unique_together': {('goal', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='日付')),
                ('value', models.FloatField(verbose_name='値')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app_core.habit', verbose_name='習慣')),
            ],
            options={
                'verbose_name': '習慣記録',
                'verbose_name_plural': '習慣記録',
                'ordering': ['-log_date'],
                'unique_together': {('habit', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='LearningTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='タグ名')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app_core.learningentry', verbose_name='学習記録')),
            ],
            options={
                'verbose_name': '学習タグ',
                'verbose_name_plural': '学習タグ',
                'unique_together': {('entry', 'tag_name')},
            },
        ),
    ]
