# Generated by Django 5.1.7 on 2025-03-22 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='現在のステップ')),
                ('total_steps', models.PositiveIntegerField(default=1, verbose_name='総ステップ数')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('target_end_date', models.DateField(blank=True, null=True, verbose_name='目標終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '学習パス',
                'verbose_name_plural': '学習パス',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('resources', models.JSONField(blank=True, null=True, verbose_name='リソース')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app_portfolio.learningpath', verbose_name='学習パス')),
            ],
            options={
                'verbose_name': '学習パスステップ',
                'verbose_name_plural': '学習パスステップ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('report_type', models.CharField(choices=[('monthly', '月次レポート'), ('quarterly', '四半期レポート'), ('yearly', '年次レポート'), ('custom', 'カスタムレポート')], max_length=20, verbose_name='レポートタイプ')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('dashboard', 'ダッシュボード表示')], default='pdf', max_length=20, verbose_name='フォーマット')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('include_learning', models.BooleanField(default=True, verbose_name='学習記録を含める')),
                ('include_habits', models.BooleanField(default=True, verbose_name='習慣記録を含める')),
                ('include_books', models.BooleanField(default=True, verbose_name='読書記録を含める')),
                ('include_goals', models.BooleanField(default=True, verbose_name='目標進捗を含める')),
                ('include_analytics', models.BooleanField(default=True, verbose_name='分析データを含める')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='portfolio_reports/', verbose_name='レポートファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_reports', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ポートフォリオレポート',
                'verbose_name_plural': 'ポートフォリオレポート',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('skill_data', models.JSONField(default=dict, verbose_name='スキルデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_maps', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スキルマップ',
                'verbose_name_plural': 'スキルマップ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
