# Generated by Django 5.1.7 on 2025-03-22 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='出典')),
                ('category', models.CharField(choices=[('success', '成功'), ('motivation', 'モチベーション'), ('learning', '学習'), ('growth', '成長'), ('consistency', '継続'), ('wisdom', '知恵')], default='motivation', max_length=20, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'モチベーション名言',
                'verbose_name_plural': 'モチベーション名言',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('badge_type', models.CharField(choices=[('streak', '継続ストリーク'), ('milestone', 'マイルストーン'), ('completion', '完了'), ('progress', '進捗'), ('special', '特別')], max_length=20, verbose_name='バッジタイプ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='アイコン名')),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='達成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '実績',
                'verbose_name_plural': '実績',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('trigger_time', models.DateTimeField(verbose_name='通知時間')),
                ('repeat_pattern', models.CharField(choices=[('none', '繰り返しなし'), ('daily', '毎日'), ('weekdays', '平日（月〜金）'), ('weekends', '週末（土・日）'), ('weekly', '毎週'), ('biweekly', '隔週'), ('monthly', '毎月')], default='none', max_length=20, verbose_name='繰り返しパターン')),
                ('end_date', models.DateField(blank=True, help_text='繰り返しの終了日', null=True, verbose_name='終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='app_core.goal', verbose_name='関連目標')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='app_core.habit', verbose_name='関連習慣')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'リマインダー',
                'verbose_name_plural': 'リマインダー',
                'ordering': ['trigger_time'],
            },
        ),
    ]
